version: '3.9'
services:
  db:
    container_name: 'rickmorty'
    image: postgres
    volumes:
      - my_pg_v:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rickmorty
      - POSTGRES_PASSWORD=rickmorty

volumes:
  my_pg_v: